apiVersion: v1
kind: Namespace
metadata:
  name: policy-gitops-generator
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: policy-gitops-generator
  namespace: policy-gitops-generator
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - policy-gitops-generator
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: policy-gitops-generator
  namespace: policy-gitops-generator
spec:
  type: Git
  pathname: https://github.com/supernoodz/gitops-policy-gen.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: kustomize
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policy-gitops-generator
  name: policy-gitops-generator-subscription
  namespace: policy-gitops-generator
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - PlacementRule
  channel: policy-gitops-generator/policy-gitops-generator
  placement:
    placementRef:
      kind: PlacementRule
      name: policy-gitops-generator-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: policy-gitops-generator
  name: policy-gitops-generator-placement
  namespace: policy-gitops-generator
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"
