apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gitops-generator
policyDefaults:
  namespace: policy-gitops-generator
  placement:
    clusterSelectors:
      vendor: "OpenShift"
  remediationAction: enforce
  severity: medium
policies:
  - name: policy-gitops-generator
    manifests:
      - path: app-policy
