apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gitops-generator
policyDefaults:
  namespace: policy-gitops-generator
  #remediationAction: enforce
  severity: medium
policies:
  - name: policy-enable-openshift-logging
    placement:
      clusterSelectors:
        logging: "enabled"
    manifests:
      - path: enable-openshift-logging
        remediationAction: enforce
  - name: policy-create-ns
    placement:
      clusterSelectors:
        namespace: "created"
    manifests:
      - path: create-ns
        remediationAction: inform
